modify controller & routes booking
akbarrahmatm/challenge-project-team-5 pull request #16
Opened 2024-04-22 12:38 UTC by MsrXvi

-  Edit Response in findBookingById
- Add Pagination in findBookingById
- Add Validation in Update and Delete if Id not found with response
- Add middleware authenticate for all route booking

2024-04-22 12:43 UTC, akbarrahmatm requested changes
Tolong diganti yaa bangg push di branch yang tadi ajaaa yahh ntar otomatis ke update kok

2024-04-22 12:43 UTC, akbarrahmatm commented on controllers/bookingController.js
> +    const car = await Booking.findOne({
Ini ganti jadi "booking" bangg

2024-04-22 12:43 UTC, akbarrahmatm commented on controllers/bookingController.js
> +    if (!Booking) {
kalau yang diatas udah diganti "booking", ganti ifnya jadi "!booking"

2024-04-22 12:57 UTC, MsrXvi commented
> Tolong diganti yaa bangg push di branch yang tadi ajaaa yahh ntar otomatis ke update kok

diganti ke branch yang mana bang

2024-04-22 12:58 UTC, akbarrahmatm commented
@MsrXvi langsung push aja kayak tadi bangg

2024-04-22 12:59 UTC, MsrXvi commented
> @MsrXvi langsung push aja kayak tadi bangg

udahng bang

2024-04-22 12:59 UTC, akbarrahmatm commented
Nice bang, udah bagus semua, approved yapss

2024-04-22 13:00 UTC, merged

2024-04-23 01:03 UTC, MsrXvi commented
> Nice bang, udah bagus semua, approved yapss

Oke bang thx